version: '3.8'

services:

  redmine:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - 80-100:3000
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_PASSWORD: 2mSGoLkpsXre
      REDMINE_DB_DATABASE: redmine
      REDMINE_PLUGINS_MIGRATE: 1
    depends_on:
      - redmine-db
    volumes:
      - /data/redmine/plugins:/usr/src/redmine/plugins
      - /home/redmine/redmine-3.3.2/files:/usr/src/redmine/files
      - /data/redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml



  redmine-db:
    image: "mysql:8"
    container_name: redmine-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2mSGoLkpsXre
      MYSQL_USER: redmine
      MYSQL_DATABASE: redmine
      MYSQL_PASSWORD: 2mSGoLkpsXre
    volumes:
      #- /home/wvandenberge/backup:/docker-entrypoint-initdb.d 
      - ./redmineSQL:/var/lib/mysql
      

