version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    depends_on:
      - redmine-db
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: redmine
      REDMINE_DB_PASSWORD: 2mSGoLkpsXre
      REDMINE_DB_DATABASE: redmine
      REDMINE_PLUGINS_MIGRATE: 1

  redmine-db:
    image: mysql:5.7.16
    container_name: redmine
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2mSGoLkpsXre
      MYSQL_DATABASE: redmine
      MYSQL_PASSWORD: 2mSGoLkpsXre
   

