version: '3.1'

services:

  redmine:
    image: redmine:3.3.9
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_PASSWORD: 2mSGoLkpsXre
      REDMINE_DB_DATABASE: redmine
      REDMINE_PLUGINS_MIGRATE: 1
    depends_on:
      - redmine-db

  redmine-db:
    image: mysql:5.7
    container_name: redmine-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2mSGoLkpsXre
      MYSQL_USER: redmine
      MYSQL_DATABASE: redmine
      MYSQL_PASSWORD: 2mSGoLkpsXre
    volumes:
      - /home/wvandenberge/backup/2023_04_17_redmine.sql:/docker-entrypoint-initdb.d 

