version: '3.1'

services:

  redmine:
    image: redmine:3.3.9
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_PASSWORD: 2mSGoLkpsXre
      REDMINE_DB_DATABASE: redmine
      REDMINE_PLUGINS_MIGRATE: 1
    depends_on:
      - redmine-db
    volumes:
      - /data/redmine/plugins:/usr/src/redmine/plugins:z
      - /data/redmine/themes:/usr/src/redmine/public/themes:z
      - /data/redmine/files:/usr/src/redmine/files:z
      - /data/redmine/log:/usr/src/redmine/log/:z
      - /data/redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml:ro
      - /data/redmine/config/en.yml:/usr/src/redmine/config/locales/en.yml:ro

  redmine-db:
    image: mariadb
    container_name: redmine-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2mSGoLkpsXre
      MYSQL_USER: redmine
      MYSQL_DATABASE: redmine
      MYSQL_PASSWORD: 2mSGoLkpsXre
    volumes:
      - /data/redmine/redmineSQL:/var/lib/mysql
      - /data/redmine/redmineSQL/config:/etc/mysql/conf.d

