version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    depends_on:
      - redmine-db
    stdin_open: true
    ports:
      - 80:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  redmine-db:
    image: mysql:5.7
    container_name: redmine_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2mSGoLkpsXre
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: 2mSGoLkpsXre
